<?php

namespace WorkshopBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByNameOrSurname($name) {
        $manager = $this->getEntityManager();
        
        $persons = $manager->createQuery('SELECT person FROM WorkshopBundle:User person WHERE person.name = :name OR person.surname = :name')
                           ->setParameter('name', $name)->getResult();
        return $persons;
    }
}
